import type { Product } from "./models"

export const demoProducts: Product[] = [
  {
    id: "prd-aren",
    sku: "DRK-001",
    name: "Kopi Susu Aren",
    description: "Espresso, susu, gula aren",
    category: "Kopi",
    price: 22_000,
    stock: 18,
    accent: "#06b6d4",
    featured: true,
    active: true,
    lowStockThreshold: 5,
    updatedAt: "2026-08-15T00:00:00.000Z",
  },
  {
    id: "prd-matcha",
    sku: "DRK-004",
    name: "Matcha Cloud",
    description: "Uji matcha, oat milk, foam",
    category: "Non Kopi",
    price: 28_000,
    stock: 7,
    accent: "#65a30d",
    active: true,
    lowStockThreshold: 5,
    updatedAt: "2026-08-15T00:00:00.000Z",
  },
  {
    id: "prd-matah",
    sku: "FOD-001",
    name: "Nasi Ayam Matah",
    description: "Ayam panggang, sambal matah",
    category: "Makanan",
    price: 35_000,
    stock: 6,
    accent: "#ea580c",
    active: true,
    lowStockThreshold: 5,
    updatedAt: "2026-08-15T00:00:00.000Z",
  },
]
